# Generated by Django 4.2.6 on 2023-10-27 16:39

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0003_expense_subcategory_alter_expense_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=6,
                validators=[
                    django.core.validators.DecimalValidator(
                        decimal_places=2, max_digits=6
                    ),
                    django.core.validators.MinValueValidator(limit_value=0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(blank=True, default=datetime.date(2023, 10, 27)),
        ),
        migrations.AlterField(
            model_name="expense",
            name="description",
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="expense",
            name="subcategory",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Gas", "Gas"),
                    ("Fuel", "Fuel"),
                    ("MPK/PKP Tickets", "MPK/PKP Tickets"),
                    ("Taxi", "Taxi"),
                    ("Financial cushion", "Financial cushion"),
                    ("Own contribution", "Own contribution"),
                    ("Investments", "Investments"),
                    ("Others", "Others"),
                ],
                max_length=30,
            ),
        ),
    ]
