# Generated by Django 4.2.6 on 2023-10-29 16:48

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0005_alter_expense_category_alter_expense_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=6,
                validators=[
                    django.core.validators.DecimalValidator(
                        decimal_places=2, max_digits=6
                    ),
                    django.core.validators.MinValueValidator(limit_value=0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("Savings", "Savings"),
                    ("Food", "Food"),
                    ("Flat rent", "Flat rent"),
                    ("Multimedia fees", "Multimedia fees"),
                    ("Transport", "Transport"),
                    ("Fund costs", "Fund costs"),
                    ("Others", "Others"),
                    ("Loans to others", "Loans to others"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(default=datetime.date(2023, 10, 29)),
        ),
        migrations.AlterField(
            model_name="expense",
            name="description",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="expense",
            name="subcategory",
            field=models.CharField(
                choices=[
                    ("Gas", "Gas"),
                    ("Fuel", "Fuel"),
                    ("MPK/PKP Tickets", "MPK/PKP Tickets"),
                    ("Taxi", "Taxi"),
                    ("Financial cushion", "Financial cushion"),
                    ("Own contribution", "Own contribution"),
                    ("Investments", "Investments"),
                    ("Others", "Others"),
                ],
                max_length=30,
            ),
        ),
    ]
