# Generated by Django 4.2.6 on 2023-10-30 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0007_alter_expense_category_alter_expense_subcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    (
                        "Savings",
                        (
                            ("Financial cushion", "Financial cushion"),
                            ("Own contribution", "Own contribution"),
                            ("Investments", "Investments"),
                            ("Others", "Others"),
                        ),
                    ),
                    (
                        "Food",
                        (
                            ("Groceries", "Groceries"),
                            ("Fast food", "Fast food"),
                            ("Eating out", "Eating out"),
                            ("Others", "Others"),
                        ),
                    ),
                    ("Flat rent", "Flat rent"),
                    ("Multimedia fees", "Multimedia fees"),
                    ("Transport", "Transport"),
                    ("Loans to others", "Loans to others"),
                    ("Fund costs", "Fund costs"),
                    ("Company expenses", "Company expenses"),
                    ("My loans to others", "My loans to others"),
                    ("Others", "Others"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(default=datetime.date(2023, 10, 30)),
        ),
    ]
