# Generated by Django 4.2.6 on 2023-10-31 09:37

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0009_alter_expense_category_alter_expense_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=6,
                validators=[
                    django.core.validators.DecimalValidator(
                        decimal_places=2, max_digits=6
                    ),
                    django.core.validators.MinValueValidator(limit_value=0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 10, 31, 9, 37, 45, 147338, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
