# Generated by Django 4.2.6 on 2023-11-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0013_alter_expense_date_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="data",
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="report_pdf",
            field=models.URLField(blank=True),
        ),
    ]
