# Generated by Django 4.2.6 on 2023-11-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0014_alter_report_data_alter_report_report_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="report_pdf",
            field=models.URLField(blank=True, null=True),
        ),
    ]
