# Generated by Django 4.2.6 on 2023-11-23 10:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0015_alter_report_report_pdf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="data",
        ),
    ]
