# Generated by Django 4.2.6 on 2023-11-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0016_remove_report_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="data",
            field=models.CharField(default=0, max_length=5000),
            preserve_default=False,
        ),
    ]
