# Generated by Django 4.2.6 on 2023-11-23 15:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0022_alter_report_report_save_path"),
    ]

    operations = [
        migrations.RenameField(
            model_name="report",
            old_name="report_pdf",
            new_name="show_report_url",
        ),
    ]
