FROM python:3.10.8-slim
RUN apt-get update
RUN apt-get -y install python3-pip python3-cffi python3-brotli libpango-1.0-0 libpangoft2-1.0-0

ENV PYTHONUNBUFFERED=1
COPY . /home_budget/
WORKDIR /home_budget
RUN pip install pip --upgrade \
    && pip install -r requirements.txt
