FROM python:3.10.8-slim
ENV PYTHONUNBUFFERED=1
COPY . /home_budget/
WORKDIR /home_budget
RUN apt-get update \
    && apt-get -y install python3-pip python3-cffi python3-brotli libpango-1.0-0 \
    libpangoft2-1.0-0 \
    && pip install pip --upgrade \
    && pip install -r requirements.txt
